accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
		path('signup/', views.signup, name='signup'),
		path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True), name='login'),
		path('logout/', auth_views.LogoutView.as_view(), name='logout'),		
		path('reset/', auth_views.PasswordResetView.as_view(
	        template_name='accounts/password_reset.html',
	        email_template_name='accounts/password_reset_email.html',
	        subject_template_name='accounts/password_reset_subject.txt', 
	        success_url='done/'
   		 ), name='password_reset'),
		path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
   			 name='password_reset_done'),
		path('reset/<slug:uidb64>/<slug:token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
   			 name='password_reset_confirm'),
		path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    		name='password_reset_complete'),
		path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', success_url='done/'),
    		name='password_change'),
		path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
    		name='password_change_done'),
		path('settings/account', views.UserUpdateView.as_view(), name='my_account')
		]

noticeboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notices.urls')),
    path('', include('accounts.urls')),
]

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
		path('', views.NoticeListView.as_view(), name='home'),
		path('notices/<int:notice_id>', views.NoticeView, name='notice_page'),
		path('notice/new', views.NewNoticePage, name='new_notice'),
		path('tag/<tag>', views.TagView.as_view(), name='tag'),
		path('tags', views.TagListView, name='tags'),
		path('u/<user>', views.UserNoticeListView.as_view(), name='user_notices'),
		]

accounts/models.py
from django.db import models

# Create your models here.

notices/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown


class Notice(models.Model):
	title = models.CharField(max_length=100)
	message = models.TextField(max_length=2000)
	created_at = models.DateTimeField(auto_now_add=True)
	tags = models.CharField(max_length=100, null=True)
	created_by = models.ForeignKey(User, related_name='posts', on_delete=models.DO_NOTHING)

	def __str__(self):
		return self.title

	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message, safe_mode='escape'))       

	def get_tags_as_list(self):
		return self.tags.split(",")[:-1]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

notices/forms.py
from django import forms
from .models import Notice

class NewNoticeForm(forms.ModelForm):

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'Description'}
        ),
        max_length=2000,
        help_text='The max length of the text is 2000.'
    )

    tags = forms.CharField(
        required=False,
        help_text='Enter tags separated by commas. Enter comma after every tag (even the last one). No spaces.')


    class Meta:
        model = Notice
        fields = ['title', 'message', 'tags']

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import SignUpForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView


def signup(request):
    if request.user.is_authenticated:
        return redirect('notices:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('notices:home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})



@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'accounts/my_account.html'
    success_url = reverse_lazy('accounts:my_account')

    def get_object(self):
        return self.request.user

notices/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404
from .models import Notice, User
from .forms import NewNoticeForm
from django.views.generic import ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class NoticeListView(ListView):
	model = Notice
	context_object_name = 'notices'
	template_name = 'notices/home.html'
	paginate_by = 10

	def get_context_data(self, **kwargs):
		return super().get_context_data(**kwargs)

	def get_queryset(self):
		queryset = Notice.objects.order_by('-created_at')
		return queryset



class UserNoticeListView(LoginRequiredMixin, ListView):
	model = Notice
	context_object_name = 'notices'
	template_name = 'notices/notices_by_user.html'
	paginate_by = 10

	def get_context_data(self, **kwargs):
		return super().get_context_data(**kwargs)

	def get_queryset(self):
		self.user = get_object_or_404(User, username=self.kwargs['user'])
		return Notice.objects.filter(created_by=self.user).order_by('-created_at')


class TagView(LoginRequiredMixin, ListView):
	model = Notice
	context_object_name = 'notices'
	template_name = 'notices/tag.html'
	paginate_by = 10

	def get_context_data(self, **kwargs):
		context_data = super().get_context_data(**kwargs)		
		context_data['tag'] = self.kwargs['tag']
		return context_data

	def get_queryset(self):
		return Notice.objects.filter(tags__icontains=self.kwargs['tag']+',').order_by('-created_at')


@login_required
def TagListView(request) :
	queryset = Notice.objects.filter(tags__isnull=False).values_list('tags', flat=True)
	tags = set(''.join(queryset).split(',')[:-1])
	return render(request, 'notices/tags.html', {'tags': tags})

@login_required
def NoticeView(request, notice_id) :
	notice = get_object_or_404(Notice, id = notice_id)
	return render(request, 'notices/notice_page.html', {'notice': notice})


@staff_member_required
def NewNoticePage(request):
	if request.method == 'POST':
		form = NewNoticeForm(request.POST)
		if form.is_valid():
			notice = form.save(commit=False)
			notice.created_by = request.user
			notice.save()
			return redirect('notices:notice_page', notice_id=notice.pk) 
	else:
		form = NewNoticeForm()
	return render(request, 'notices/new_notice.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'notices/base.html' %}
{% load static %}

	{% block title %}Log In{% endblock %}

    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
    {% endblock %}

    {% block navbar %}
    {% endblock %}


	{% block content %}

		<div class="row justify-content-center login-form">
	      <div class="col-lg-7 col-md-8 col-sm-12">
	        <div class="card">
	          <div class="card-body">
	            <h3 class="card-title">Log In</h3>
	            <form method="post" novalidate>
	              {% csrf_token %}
  				  <input type="hidden" name="next" value="{{ next }}">
	              {% include 'notices/form.html' %}
	              <button type="submit" class="btn btn-primary btn-block">Submit</button>
	            </form>
	          </div>
	          <div class="card-footer text-muted text-center">
	            Don't have an account? <a href="{% url 'accounts:signup' %}">Create one.</a>
	          </div>
	        </div>
	         <div class="text-center py-2">
          	<small>
            	<a href="{% url 'accounts:password_reset' %}" class="text-muted">Forgot your password?</a>
          	</small>
        </div>
	      </div>
	    </div>

	{% endblock %}

accounts/templates/accounts/my_account.html
{% extends 'notices/base.html' %}

{% block title %}My account{% endblock %}

<!-- {% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %} -->

{% block content %}
  <div class="row mt-5">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'notices/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'notices/base.html' %}
{% load static %}


{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}


{% block title %}Change password{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'notices/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'notices/base.html' %}
{% load static %}


{% block title %}Change password successful{% endblock %}



{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'notices:home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'notices/base.html' %}
{% load static %}

{% block title %}Reset your password{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block navbar %}
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'notices/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'notices/base.html' %}
{% load static %}


{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block title %}Password changed!{% endblock %}

{% block navbar %}
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'notices/base.html' %}
{% load static %}


{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block navbar %}
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'notices/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'notices/base.html' %}
{% load static %}


{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks

accounts/templates/accounts/signup.html
{% extends 'notices/base.html' %}
{% load static %}

    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
    {% endblock %}

    {% block navbar %}
    {% endblock %}


	{% block content %}

		<div class="row justify-content-center card-form">
	      <div class="col-lg-7 col-md-8 col-sm-12">
	        <div class="card">
	          <div class="card-body">
	            <h3 class="card-title">Sign up</h3>
	            <form method="post" novalidate>
	              {% csrf_token %}
	              {% include 'notices/form.html' %}
	              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
	            </form>
	          </div>
	          <div class="card-footer text-muted text-center">
	            Already have an account? <a href="#">Log in</a>
	          </div>
	        </div>
	      </div>
	    </div>

	{% endblock %}

notices/templates/notices/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}Notice Board{% endblock %}</title>


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/notices.css' %}">
    {% endblock %}
    
</head>
<body>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="{% url 'notices:home' %}">Notice Board</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            {% block navbar %}

                <div class="collapse navbar-collapse" id="mainMenu">
                    {% if user.is_authenticated %}
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
                            <a class="dropdown-item" href="{% url 'accounts:my_account' %}">My Account</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                          </div>
                        </li>
                        <form class="form-inline ml-auto">
                        {% if user.is_staff %}
                         <a href="{% url 'notices:new_notice'%}" class="btn btn-primary mx-2">New notice</a>
                        {% endif %}
                         <a href="{% url 'notices:tags'%}" class="btn btn-primary mx-2">View tags</a>
                        </form>

                      </ul>
                     {% else %}
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                          <a class="nav-link btn btn-outline-secondary" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Student
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'accounts:signup' %}">Signup</a>
                          </div>
                        </li>

                        <li class="nav-item dropdown">
                          <a class="nav-link btn btn-outline-secondary ml-2" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Teacher
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                          </div>
                        </li>
                      </ul>

                  {% endif %}                     
                </div>
            {% endblock %}
          </div>
        </nav>

    <div class="container">

    {% block content %}
    {% endblock %}

    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

notices/templates/notices/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

notices/templates/notices/home.html
{% extends 'notices/base.html' %}

{% load humanize %}

{% block title %}
  Home - {{ block.super }}
{% endblock %}

{% block content %}
	

		<ol class="breadcrumb my-4">
		    <li class="breadcrumb-item active"> {% block breadcrumb %} Notices {% endblock %}</li>
		</ol>
	    <table class="table">
	    	<thead class="thead-dark">
	    		<tr>
	    			<th>Title</th>
	    			<th>User</th>
	    			<th>Time</th>
	    		</tr>
	    	</thead>
	      <tbody>
	      	{% if notices %}
		        {% for notice in notices %}
		          <tr>
		            <td>
		              <a href="{% url 'notices:notice_page' notice.id %}"> {{ notice.title }} </a>
		            </td>
		            <td>
		              <a href="{% url 'notices:user_notices' notice.created_by %}">{{ notice.created_by }} </a>
		        	</td>
		            <td>{{ notice.created_at|naturaltime }}</td>
		          </tr>
		        {% endfor %}
		      </tbody>
		     {% endif %}
	    </table>

		 {% if is_paginated %}
		    <nav aria-label="Topics pagination" class="my-4">
		      <ul class="pagination justify-content-center">
		        {% if page_obj.has_previous %}
		          <li class="page-item">
		            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		          </li>
		        {% else %}
		          <li class="page-item disabled">
		            <span class="page-link">Previous</span>
		          </li>
		        {% endif %}

		        {% for page_num in paginator.page_range %}
		          {% if page_obj.number == page_num %}
		            <li class="page-item active">
		              <span class="page-link">
		                {{ page_num }}
		                <span class="sr-only">(current)</span>
		              </span>
		            </li>
		          {% else %}
		            <li class="page-item">
		              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
		            </li>
		          {% endif %}
		        {% endfor %}

		        {% if page_obj.has_next %}
		          <li class="page-item">
		            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
		          </li>
		        {% else %}
		          <li class="page-item disabled">
		            <span class="page-link">Next</span>
		          </li>
		        {% endif %}
		      </ul>
		    </nav>
		  {% endif %}
{% endblock %}

notices/templates/notices/new_notice.html
{% extends 'notices/base.html' %}

{% load widget_tweaks %}

{% block title %}New Notice{% endblock %}

{% block content %}

	<form method="post" novalidate class="mt-5">
	    {% csrf_token %}
    	{% include 'notices/form.html' %}
	    <button type="submit" class="btn btn-success">Post</button>
	</form>



{% endblock %}

notices/templates/notices/notice_page.html
{% extends 'notices/base.html' %}
{% load humanize %}

{% block content %}
    <div class="card mb-2 mt-5">
      <div class="card-body p-3">

		<h3 class="p-3">{{ notice.title }}</h3>

		<div class="row mb-3 p-3">
		  <div class="col-6">
		    <strong class="text-muted">by {{ notice.created_by }}</strong>
		  </div>
		  <div class="col-6 text-right">
		    <small class="text-muted">posted {{ notice.created_at|naturaltime }}</small>
		  </div>
		</div>

		<div class="p-3">{{ notice.get_message_as_markdown }}</div>

		{% if notice.tags %}
			<span class="p-3">
			Tags:
			</span>
			<span class="p-3">
				{% for tag in notice.get_tags_as_list%}
					<a href="{% url 'notices:tag' tag %}"> {{ tag }} </a>

				{% endfor %}
			</span>
		{% endif %}

	    	
	   </div>
	</div>

{% endblock %}

notices/templates/notices/notices_by_user.html
{% extends 'notices/home.html' %}


{% block breadcrumb %} Notices by <strong>{{ user }}</strong>. {% endblock %}

notices/templates/notices/tag.html
{% extends 'notices/home.html' %}


{% block breadcrumb %} Notices with '{{ tag }}' tag {% endblock %}

notices/templates/notices/tags.html
{% extends 'notices/base.html' %}

{% load humanize %}

{% block title %}
  Tags - {{ block.super }}
{% endblock %}

{% block content %}
	
		<ol class="breadcrumb my-4">
		    <li class="breadcrumb-item active"> Tags</li>
		</ol>
	    <table class="table">
	      <tbody>
	      	{% if tags %}
		        {% for tag in tags %}
		          <tr>
		            <td>
		              <a href="{% url 'notices:tag' tag %}"> {{ tag }} </a><br>
		            </td>
		          </tr>
		        {% endfor %}
		      </tbody>
		     {% endif %}
	    </table>

{% endblock %}